### PR TITLE
Update user guide and tests, Fix minor bugs

### LINKED ISSUE #159: [PE-D] Slight typo in the UG
Slight typo

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: darren2pro/ped#4

### LINKED ISSUE #171: [PE-D] Bug in displaying timing for scheduling
I got this bug after entering -friend --schedule a -p 0 24 2 -f 1

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: itsyme/ped#7

### LINKED ISSUE #177: [PE-D] Wrong error message shown
## Description
Editing a friend gives me the wrong error message if I leave the name field blank.

## How to reproduce the bug?
1. Boot up the appplication
2. Add a friend using the command without a specified name `friend --add Draco`
3. Try to edit the friend `friend --edit Draco -n`

## What happened?
The following error message will show:

## What should happen?
I would assume I would get a more useful error message regarding the name instead, such as "Name cannot be left blank" or "Name provided must be a single word"

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: calvintanwj/ped#3

### LINKED ISSUE #186: [PE-D] Example for list command mentions name
This is what is written in the UG, the summary talks about how the friends are filtered by friend id that contains any of the given keywords.

But in the second example they say `friend --list ta` lists all friends that have `ta` in their name. I think it's a small typo, shouldn't it be `ta` in their FRIEND_ID instead?

The same issue also for your `game --list`

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: calvintanwj/ped#8

### LINKED ISSUE #190: [PE-D] "friend --schedule" start_hour and end_hour format too restrictive
Currently start_hour and end_hour in "friend --schedule" command must be integers between 0 and 24, thus users can only schedule whole hour time slots. However this may be too restrictive as a person's availability can lie at any time of an hour like 20:30 or even 20:11.

In fact, Java has an built-in API for parsing and managing date and time: https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html.
If you use this, you can type in any time in any format (like 23:59:01), and you can even schedule particular dates. It is recommended to check this out :D

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: JinxinZhao315/ped#6

### LINKED ISSUE #202: Update logic package tests
Update test in logic package, excluding command-specific tests

### PR DESCRIPTION
**Pull request by MarcusTXK**
### Description
* Update logic package tests to attain 100% method and lines coverage, excluding friend and game commands
image

* Update list and schedule user guide documentation
* Update schedule to display midnight as 2400

### Issues
* Resolves #177 
* Resolves #171 
* Resolves #190
* Resolves #186 
* Resolves #171 
* Resolves #159 
* Resolves #202 

### Screenshots
* Issue #177 Fix: (Note: I fixed it for all other commands as well)
image

* Issue #177 
image

### CODE REVIEW

File: src/main/java/seedu/address/model/util/DayTimeUtil.java [hunk 1]
```diff
@@ -2,28 +2,25 @@
...
  * Helper function for managing conversions of day and time
  */
 public class DayTimeUtil {
-    /**
-     * Used for validation that String follows the 24 hour format without minutes eg, 0100, 0200, etc
-     */
-    private static final Pattern TIME_FORMAT = Pattern.compile("^([01][0-9]|2[0-3])(00)$");
+
+    private static final int SMALLEST_TIME = 0;
+    private static final int LARGEST_TIME = 24;
```
Comment (YeluriKetan) [inline src/main/java/seedu/address/model/util/DayTimeUtil.java:13]: Good catch on the use of magic literals.

**Comment by YeluriKetan** [comment]
> * Resolves [[PE-D] Bug in displaying timing for scheduling #171](https://github.com/AY2122S1-CS2103T-W13-4/tp/issues/171)
> * Resolves [[PE-D] "friend --schedule" start_hour and end_hour format too restrictive #190](https://github.com/AY2122S1-CS2103T-W13-4/tp/issues/190)
> * Resolves [[PE-D] Example for list command mentions name #186](https://github.com/AY2122S1-CS2103T-W13-4/tp/issues/186)
> * Resolves [[PE-D] Bug in displaying timing for scheduling #171](https://github.com/AY2122S1-CS2103T-W13-4/tp/issues/171)

#171 linked twice.

> * Issue [[PE-D] Wrong error message shown #177](https://github.com/AY2122S1-CS2103T-W13-4/tp/issues/177)
>   image

Wrong issue description of the screenshot.

**Review by YeluriKetan — APPROVED** [review]
LGTM. Great job on the magic literals and test coverage. 
Please fix your PR description to avoid any future confusion.
