### PR TITLE
Update regex, error messages bugs from [PED]

### LINKED ISSUE #176: [PE-D] Issue with edit friend command
## Description
Currently, unable to edit a friend name's for a friend I created.

## How to reproduce the bug?
1. Boot up the appplication
2. Add a friend using the command without a specified name `friend --add -n`
3. Try to edit the friend `friend --edit -n -n Bob`

## What happened?
The following error message will show:

## What should happen?
I would assume I would be able to assign the name Bob to my friend with `FRIEND_ID` -n. I suspect that the way the `friend --edit command` is being parsed is confused about the duplicate `-n`. I think to begin with, it seems that it should not be possible to add a friend with a `FRIEND_ID` with `-n`. Since in your GUI, it says `FRIEND_ID` provided must be a single word and only contain alphanumeric characters. 

Showing it is possible to add a friend with `FRIEND_ID` of `-n`:

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: calvintanwj/ped#2

### LINKED ISSUE #180: [PE-D] Minor issue with delete error message
## Description
Deleting a friend with an invalid `FRIEND_ID` gives me a not particularly useful error message.

## How to reproduce the bug?
1. Boot up the appplication
2. Run the command `friend --delete FriendIdWithSpecialCharacter!`

## What happened?
The following error message will show:

## What should happen?
I would assume I would get a more useful error message such as your error message "This friend does not exist in your list", same as when I attempt to delete friends with valid `FRIEND_ID`, or even "FRIEND_ID can only contain alphanumeric characters". However, this is a pretty minor issue, but I personally feel that the error message "Invalid command format" is not very helpful and also deceiving, since I've technically followed the format correctly.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: calvintanwj/ped#4

### LINKED ISSUE #181: [PE-D] GAME_ID allows "-"
## Description
Same as your `FRIEND_ID`, I can add games with `GAME_ID` containing "-n", which once again causes issue with your parser and had repercussions on your commands like `link`

## How to reproduce the bug?
1. Boot up the appplication
2. Run the command `game --add -g`
3. Attempt to link the game with a friend, by running the command `friend --link Draco -g -g -u Draco123`

## What happened?
The following error message will show:

## What should happen?
I guess to begin with I should not be able to create a games with such a `GAME_ID`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: calvintanwj/ped#5

### LINKED ISSUE #215: Update validation regex for data classes
Update validation regex for 
- `FriendId` - alphanumeric, single word, max 20 chars
- `FriendName` - non hyphen, max 20 chars
- `GameId` - alphanumeric, single word, max 20 chars
- `UserName` - non hyphen, max 20 chars

### PR DESCRIPTION
**Pull request by YeluriKetan**
# Changes
- Update validation regex for `FriendId`, `FriendName`, `GameId` and `UserName`
- Fix error messages for `get` and `delete` commands
- Update ParserUtil
- Update related tests for all the above

# Issues
- Fixes #176 
- Fixes #180 
- Fixes #181 
- Fixes #215 

# Preview
- Validation regex for `FriendId` and `GameId`
image

- Validation regex for `FriendName` and `UserName`
image

# Testing
All commands work with the bugs fixed.

### CODE REVIEW

File: src/main/java/seedu/address/model/friend/FriendId.java [hunk 1]
```diff
@@ -11,9 +11,14 @@
 
     public static final String MESSAGE_EMPTY_FRIEND_ID =
             "FRIEND_ID cannot be empty.";
-    public static final String MESSAGE_INVALID_CHARACTERS = "FRIEND_ID provided must be a single word and only contain "
-            + "alphanumeric characters.";
-    public static final String VALIDATION_REGEX = "^[a-zA-Z0-9._-]+$";
+    public static final String MESSAGE_INVALID_CHARACTERS = "FRIEND_ID provided must be a single alphanumeric word, "
+            + "of maximum 20 characters.";
```
Comment (MarcusTXK) [inline src/main/java/seedu/address/model/friend/FriendId.java:15]: I am not sure why, but this sounds slightly weird to me. Perhaps we could rephrase it to be e.g.
"FRIEND_ID provided must be a single alphanumeric word, up to a maximum of 20 characters." ?

File: src/test/java/seedu/address/model/friend/FriendNameTest.java [hunk 2]
```diff
@@ -27,15 +27,18 @@ public void isValidName() {
...
-        assertTrue(FriendName.isValidName("peter the 2nd")); // alphanumeric characters
-        assertTrue(FriendName.isValidName("Capital Tan")); // with capital letters
-        assertTrue(FriendName.isValidName("David Roger Jackson Ray Jr 2nd")); // long names
+        assertTrue(FriendName.isValidName("Peter123")); // single word
+        assertTrue(FriendName.isValidName("Peter jack123")); // multi-word
+        assertTrue(FriendName.isValidName("`~!@#$%^&*()_=+[{]}")); // all special characters available
+        assertTrue(FriendName.isValidName("\\|;:'\",<.>/?")); // on an average keyboard
+        assertTrue(FriendName.isValidName("Peter jack#123 @<>")); // with special characters
+        assertTrue(FriendName.isValidName("p")); // short name - 1 char
+        assertTrue(FriendName.isValidName("David Roger Evans Jr")); // long names - 20 chars
```
Comment (MarcusTXK) [inline src/test/java/seedu/address/model/friend/FriendNameTest.java:42]: Nice work on the comprehensive tests

File: src/test/java/seedu/address/storage/JsonAdaptedFriendTest.java [hunk 3]
```diff
@@ -17,7 +17,7 @@
 
 // TODO: Update tests for FriendId and Games based on UG specs
```
Comment (MarcusTXK) [inline src/test/java/seedu/address/storage/JsonAdaptedFriendTest.java:18]: I know this wasn't written by you, but consider removing it as the tests have been updated.

**Review by MarcusTXK — APPROVED** [review]
LGTM, some minor nitpicks. I tested it and the regexes all seem to work well. Nice job on writing the tests!
